### ISSUE TITLE
Tray/Drive colour ignores common Configuration changes

### ISSUE THREAD

**Issue by circulon** [olehj/disklocation#124]
Hi 
Can I first say this plugin is really helpful!  Great work!

ok now to the Bug

Description:
The common drive colours only get assigned to a tray on the first assignment.
After this initial assignment the colour gets assignerd as the custom colour and can only be changed on a per drive basis.

How to replicate: 
- Make sure no drives have been assigned (delete the db works great!)
 - Set some arbitrary colour for the parity and/or other drive types.
- assign some drives to particular trays noting current colours.
- Decide coulour scheme clashes for some reason so change the Parity or other drive type backfround colour in the Common configuration area.
- Save settings in the common configuration area.
- Reload the page to make sure the data is reloaded.
- open the Tray Allocations and note that the colour you changed the drive type to is the same as it was previously.  

Additional observations: 
- The previous colour is also shown as the custom colour on the tray allocations and in the the tray layout area.
- unallocating the drive from the tray save and force rescan of all drives keps the originally assigned colour.
- On the Tray allocations tab
-- The  unassigned Trays  in the Quick layout view get a background colour of  rgb(0,0,0) which  is not the unassigned trays background colour.
-- I noted this as I use a high contrast plugin on firfox and chrome and the unassigned trays just show the number and no colour
-- this can be checked by comparing the div elements of an assigned and unassigned 
tray items

Possible fixes:
- during a force rescan reset the tray/drive colour to the common colour unless the custom colour has been deliberately altered
- add a checkbox next to the custom colour in the tray allocations page to "reset colour to defdault" when saving changes on that page
- add a checkbox in the custom solour cell of the tray allocations that denotes a custom solour is in use and has been deliberately set. Unchecking this box uses the default comm on settings
  

Current Workarounds for this issue:
1. Delete the DB via the system files tab and start from scratch with colour assignments (take a screensot of the common colours before you do this)
2. alter each drive individually to reflect the  preferred common colour settings.

Thanks 
Keep up the great work

**Comment by olehj** [comment]
It was a ton of information here, so I will just make sure about some things to test first:

To reset the color for each device, you should select the "gray" color (first shown in the box, this color is the "empty" color so it might be different if you have chosen a different color), regardless, it will reset the color to be the default assigned color for parity/data/cache/unassigned.

"Force scan all" will not be part of any color scheme, it will only scan the drives for SMART data and availability. The colors are stored in the database as per drive.

It was mainly never any intention to make a custom color per drive for parity/data/cache drives, as they are already specified as a whole, but some people might like options so I keep it enabled. But to reset, the "empty" (gray as standard) must be checked per drive and saved.

It will conflict if you choose a custom color for some Unraid assigned device and then change the entire group.

Adding a full color reset button could of course be implemented one day as an additional function. But for now, use the "gray/empty" color to reset per drive.

**Comment by circulon** [comment]
Apologies for the overly verbose bug report.

Thanks for the info
Choosing the empty colour did indeed reset it back to the new one selected in common settings.

this was not immediately obvious though and you have to turn on the help in the tray allocations page to find out how to reset the colour.

Maybe adding some help blurb to the common colour settings would be beneficial, as this issue is directly visible in the overview of the tray layout at the bottom of the common page which indicates the colours and layout of drives.

**Comment by olehj** [comment]
I should probably add a hint at least to use "Help" in general, looks like more people forget the Help function in Unraid.

**Comment by circulon** [comment]
Yeah that would be good.

Maybe a checkbox under the common colour settings like : 
"update existing non custom tray allocations" ? 
this option would then make it obvious that the changes will only affect new allocations if not checked.

My point about this is as "data" drives are over 90% of the drives in use.
So  if you change the colour for a data drive tray after they are already allocated (10-20 data drives as an example), you need to set every single data drive colour back to "empty" just to see if its suitable and easy on the eyes.
 
Thanks

**Comment by olehj** [comment]
Update 2020.02.19 rolled out with a fix that should help in many cases.
