### ISSUE TITLE
Feature Request: Show custom data field

### ISSUE THREAD

**Issue by Mikki-10** [olehj/disklocation#147]
Hi I think it would be nice if it was possible to show a custom smart data field.

eg I will like to see id 241 (Total lbas written) and 242 (Total lbas read) for my drives in the total disk information overview, and when hover over them they are translated into TB GB format.
https://www.virten.net/2016/12/ssd-total-bytes-written-calculator/

I know i can not get both, eg make a custom field and then translate the value but either way I will be happy, I will just as a minium like to be able to see id 241 and 242 in the disk overview :)

**Comment by olehj** [comment]
Maybe in the future, but I rather strip down the SMART functions as they are already a part of Unraid which does a great job with it.

**Comment by olehj** [comment]
There's too much difference between drive types to include this specific request. I will close this as it won't happen. Sorry I can't fulfill your wishes here. SMART data is a hell the parse sometimes.

**Comment by olehj** [comment]
@Mikki-10 this (LBAs) will be implemented in the Overhaul '24 milestone.
