### ISSUE TITLE
Adding unassigned/non-array devices

### ISSUE THREAD

**Issue by alcorza** [olehj/disklocation#148]
Hi there, this is more of a feature enhancements request. on unRAID, I have the unassigned devices plugin for an NVMe SSD (used off array). It'd be great for disklocation to detect non-array devices so they can be included in the layout.

**Comment by olehj** [comment]
The plugin doesn't care about whether the drive is in the unraid array or not, if it's not detected after a "Force Scan All", then it's simply missing some values to be recognized by "lsscsi -u -g" and "smartctl <device>"

Nothing more I can do here I guess. But you can output the above commands so I can have a look.

**Comment by olehj** [comment]
Nothing more to be done here, closing issue which might be specific to a single drive
