### ISSUE TITLE
Allow choice of (or simply default to) "stacked" in addition to current 'Side by side' enclosure display

### ISSUE THREAD

**Issue by teambvd** [olehj/disklocation#156]
The current UI layout functions perfectly for single enclosure, or single + small multi-bay, but for those with two or more disk locations which have different disk layouts, the current rendering method appears jilted:

![Disk_location](https://user-images.githubusercontent.com/70113838/93558154-67a13f80-f942-11ea-81cb-4d04ecc49f8e.png)

Moving the plugin over to the arrays section can help, but only at higher resolutions as the array column expands to fill available browser space (so lower res screens, or non-full screen browsers would still be impacted similarly. Not only the dashboard widget suffers from this unfortunately, and to a much larger degree:
![Screen Shot 2020-09-18 at 12 11 27 AM](https://user-images.githubusercontent.com/70113838/93559206-cff12080-f944-11ea-8a9d-7f08230b8045.png)

This would have the additional benefit of making it simpler for people to accurately display their enclosures:
* The forced drive count option's necessity is removed, solved by simply creating another enclosure image that accurately represents the setup
* The forced count method additionally only functions as one would expect under specific scenarios - if the grids (4x3, 1x8, etc) are too different, unexpected outcomes result.
* For those with racked homelabs, the image they see will mirror their rack

**Comment by olehj** [comment]
Removed the <table> and chose to use <div> with float instead. Should align itself automagically where it fits best.
