### ISSUE TITLE
nvme drive missing is drive listing.

### ISSUE THREAD

**Issue by tulathron** [olehj/disklocation#158]
Seems something about the SCSI output doesn't bring in all the nvme drives. It displays the first nvme drive found but not the second drive.

![image](https://user-images.githubusercontent.com/21177358/105746757-75c12700-5f05-11eb-876a-75145a46e0dd.png)

Seems someone spotted this same issue in the forums but no issue had been created.  Let me know if there is any other output you require.

**Comment by olehj** [comment]
lsscsi changed the output in Unraid 6.9, new release will be updated and require Unraid 6.9 from next release.
