### ISSUE TITLE
Feature Request: SCSI Enclosure Services (SES2) support

### ISSUE THREAD

**Issue by ciroiriarte** [olehj/disklocation#159]
Hello!,

Would it be possible to support SES2 present in some cages like the Supermicro cse-m35tqb?.

This includes signaling of different LEDs:
- Activity LED
- Failure LED

The idea is to reflect status not only as a web page but on the physical LEDs too.

Ref:

https://www.supermicro.com/manuals/other/CSE-M35TQ.pdf
https://github.com/intel/ledmon
https://en.m.wikipedia.org/wiki/SES-2_Enclosure_Management

**Comment by olehj** [comment]
Don't expect anything from this, as I can't test it myself it will be hard to do. Must be some kind of scripts out there that can handle this by reading smart data or something else? I wouldn't trust Disk Location to be super accurate anyway about reporting faulty drives.

**Comment by olehj** [comment]
This will be a bit outside the scope of the plugin, and too many different systems to take care of. I will close this as it is very unlikely this will happen.
