### ISSUE TITLE
Possibility to offset disk trays

### ISSUE THREAD

**Issue by horfic** [olehj/disklocation#163]
Hi,
first of all i really like the plugin as it provides a good fast overview and is easy to configure.

Now to my wanted enhancement, would it be possible to offset disk tray layouts?

E.g. That i got a 1x4 grid at the bottom and next to it a new grid like 1x11

The offset could also be used to start tray count with a different number than 0 and 1.

I'm asking as i got a "L" form of trays in my server tower and can't really display it correctly.
A different solution would be to hide/remove from a 2x11 grid certain slots to get to an individual form like a "L" form

cheers,
Horst

**Comment by olehj** [comment]
Currently I guess the best option might be to create 2x11 and just leave the unused slots as "empty"

This plugin wasn't intended to create all various design layouts out there. But I might add some "hidden" trays in the future, and starting from different numbers should probably be ok to fix later as well. 

For now, rather mark the chassis and each group with a logic name.

If I wouldn't hate javascript, I might have added more flexible layout solutions. Maybe in the future as well (probably not).
