### ISSUE TITLE
Disk Location is not Showing up in Tools menu

### ISSUE THREAD

**Issue by Vilhjalmr26** [olehj/disklocation#164]
New install of disklocation, I can access the settings from Settings area, but disklocation does not appear anywhere in the Tools section that I can see.

![image](https://user-images.githubusercontent.com/28853873/119387019-f3b3f580-bc8d-11eb-8097-da042fe30d08.png)

**Comment by olehj** [comment]
Check now and please give feedback if the last update has resolved it. Thanks

**Comment by olehj** [comment]
Closing this as it should be fine, reopen if not..
