### ISSUE TITLE
SQL error during installation

### ISSUE THREAD

**Issue by P6g9YHK6** [olehj/disklocation#174]
I am getting the following during the installation:

Adding disks into database, please wait... this might take a while...

**Warning: SQLite3::exec(): no such table: settings in /usr/local/emhttp/plugins/disklocation/pages/sqlite_tables.php on line 465
no such table: settings
Warning: SQLite3::exec(): cannot start a transaction within a transaction in /usr/local/emhttp/plugins/disklocation/pages/sqlite_tables.php on line 498
cannot start a transaction within a transaction
Warning: SQLite3::query(): Unable to prepare statement: 1, no such table: disks in /usr/local/emhttp/plugins/disklocation/pages/sqlite_tables.php on line 506

Fatal error: Uncaught Error: Call to a member function fetchArray() on bool in /usr/local/emhttp/plugins/disklocation/pages/sqlite_tables.php:507
Stack trace:
#0 /usr/local/emhttp/plugins/disklocation/pages/system.php(61): require_once()
#1 {main}
thrown in /usr/local/emhttp/plugins/disklocation/pages/sqlite_tables.php on line 507**

Plugin installed successfully!
plugin: disklocation-master.plg installed

Obviously nothing is installed.

**Comment by olehj** [comment]
Which Unraid version so you have? Did you try to delete database and reinstall the plugin? 

I tried to install from plain state from Community Apps and everything worked as expected.

**Comment by P6g9YHK6** [comment]
Version: 6.9.2 

and the database in the plugins directory is correctly removed on uninstall so yes it's clean every time.

**Comment by olehj** [comment]
The database is not removed on an uninstall. Is the USB stick/Unraid drive read-write? Can you create any file in /boot/config/plugins/ manually?

`touch /boot/config/plugins/testfile`

**Comment by PintjesBier** [comment]
Can confirm removing the database fixed this issue for me!

**Comment by P6g9YHK6** [comment]
Solved i tried to check "/usr/local/emhttp/plugins/disklocation/" rather than "/boot/config/plugins/"
after deleting the database in /boot/config/plugins/ it worked like a charm.
but there is an issue after all with the install process if i am not the only one that it happened to.

**Comment by olehj** [comment]
I'm interested in knowing if this is still a problem for someone? I haven't really done anything with it, but Unraid has changed the way plugins are installed in the later versions (6.11?).

**Comment by olehj** [comment]
Closing this issue, as I haven't heard anyone having this problem recently. Might be fixed by the new plugin system by Unraid.
