### ISSUE TITLE
Read purchase date / warranty period from UnRAID

### ISSUE THREAD

**Issue by Leseratte10** [olehj/disklocation#176]
After I installed the plugin on UnRAID 6.9.2, I had to enter the purchase date and warranty duration for all my drives into the Disk Location plugin settings, even though I had already entered that into the UnRAID drive settings (Main -> Disk X -> Identity -> "Date of purchase" and "warranty period") before. 

Am I doing something wrong, or is the plugin not reading from that data? If so, can the plugin be altered to just display that data and/or write to these data fields instead of its own database? Otherwise people have to enter that data twice in two different locations which can lead to inconsistencies ...

**Comment by olehj** [comment]
Does this happen -after- you have saved the drive in its allocation? It might not read and store this data during "force update", but after assigned the disk to a tray. Long time ago I wrote this part. It is supposed to do as you say, the data entered in Unraid's interface will override whatever you're typing into the plugin itself (and not the other way around).

**Comment by Jarsky** [comment]
Im having the same issue. Using UnRAID 6.11.5 but the feature has never worked for me. 
I entered all the Manufacture, Purchase and Warranty Dates in the UnRAID drive settings same as the OP. 
I've assigned the drives to their trays. I've tried a force update also.Lastly I have deleted the database, deleted the plugin and reinstalled it and started fresh, and still the same.

**Comment by olehj** [comment]
This will be fixed next release (for Unraid 6.12 and later), no new releases for earlier versions.
