### ISSUE TITLE
Warnings about non-numeric values posted in some situations

### ISSUE THREAD

**Issue by olehj** [olehj/disklocation#187]
Variables checked for being set is now instead checked if they're numeric.

**Comment by olehj** [comment]
device.php line #231 and possible more.

**Comment by lrdfrd** [comment]
I have this error.

UnRaid Version 6.10.3 2022-06-14

**Comment by olehj** [comment]
> I have this error.
> 
> UnRaid Version 6.10.3 2022-06-14

Do you have the newest version? If you do: which line(s) does it complain about?

**Comment by chriscarpenter12** [comment]
For me it shows on 231 when testing this plugin.

> Warning: A non-numeric value encountered in /usr/local/emhttp/plugins/disklocation/pages/devices.php on line 231

**Comment by olehj** [comment]
This fix was never really released. But as I haven't updated anything else since June, I have merged the code now so you can go ahead and update and test it.
