### ISSUE TITLE
Multiple spinning drives showing as SSD

### ISSUE THREAD

**Issue by Nach0-Stallion** [olehj/disklocation#19]
Hi, I have recently installed this plugin to my new server and have found that it is showing most of my NAS type drives
![tempsnip](https://user-images.githubusercontent.com/47112682/51844296-9e3ad880-2360-11e9-9fd6-50a62449d438.png)
 (WD RED) as SSD rather than 7200 or 5400RPM drives

Some work ok, but most show as SSD.. the server is currently building creating the array for the first time if that makes a difference?
Cheers.

**Comment by olehj** [comment]
I don't think it matters if the server is creating the array or not, it really depends on the SMART data. 

However, I see the code will treat value of 0 and text as the same and store both as 0 in the database. SSD report themselves as "Solid State Device", while HDD reports the actual value if it exists. So it is likely that your WD drives does not report the rotation speeds at all (I know that my WD Red 3TB does though). Anyway, I will modify the code to store "-1" for SSD instead. It will be fixed next release.

**Comment by Nach0-Stallion** [comment]
What a lightning quick response!, Cheers for that, i wasn't sure as im very new to unraid and wasn't sure it your app was pulling data from an area that may have been too busy. super handy app, thank you!
