### ISSUE TITLE
raid p410 controller

### ISSUE THREAD

**Issue by thehatch2002** [olehj/disklocation#191]
So, I have two unraid servers which I have this plug on.  Both have p410 controllers and 1 has a diskshelf.  I have noticed that if you use this plug in with raid p410 controller, it will only show one disk even though you have say, three logical drives on that raid card.  The same server shows all the drives on the diskshelf.  I am not sure if you are able to make an update for this to list all the logical drives on a raid controller.  The one server I have 4 drives in a raid 5 configuration times 2, only shows 1 logical drive out of the two.

**Comment by olehj** [comment]
It all goes down to what "lsscsi" outputs, if that command only see one drive of the controller, then there's not much I can do which won't make me create a whole bunch of hacks to make it work.

This plugin is targeted for more typical Unraid installs with software raids and ...unraid with drives connected to the motherboard or HBA cards etc.

**Comment by olehj** [comment]
As reported by an I410 controller, the serial numbers are identical across the logical volumes it creates. This plugin requires unique serial numbers per drive/device to function. This may be the same issue here, so I am closing this as it won't be fixed.
