### ISSUE TITLE
Compatibility with unraid 6.12

### ISSUE THREAD

**Issue by ashishpandey** [olehj/disklocation#192]
plugin has been marked incompatible with 6.12 rc1
https://forums.unraid.net/topic/77302-plugin-disk-location/?do=findComment&comment=1240680

**Comment by olehj** [comment]
It's soon available, just gonna go through more of the code before I release it.

**Comment by ashishpandey** [comment]
thanks for the update / fix. But seems the update cannot be installed until unraid 6.12, which means we have to first update unraid, at which point the dashboard will be broken and then we need to update plugin and expect it to work again

Any chance this can be compatible with 6.11.5 so that we can update plugin prior to unraid upgrade? that is how most other plugins have built 6.12 compatibility

**Comment by olehj** [comment]
I have no time for this. Leave the installed version until you upgrade, then enjoy the new update. Otherwise, developer release will work except from the dashboard.
