### ISSUE TITLE
Dropped from the Unraid forums???

### ISSUE THREAD

**Issue by quadcom** [olehj/disklocation#195]
I got a notification that there was an update to this today.

Tried to install it and was returned with an error stating that Unraid 6.12 was required, which isn't out as yet.

Went to look at the support thread to figure out what was going on, and the support thread is gone.

https://forums.unraid.net/topic/77302-plugin-disk-location/

**Comment by olehj** [comment]
Ye, I dunno what happened there. The issue is reported, so let's find out what happens. The release will happen today, and the changelog is updated.

**Comment by olehj** [comment]
The plugin itself will be added as soon as its confirmed by some moderators as it had broken Dashboard for 6.12

**Comment by olehj** [comment]
It's back up and fixed!
