### ISSUE TITLE
Max Temp set at 12 degrees F

### ISSUE THREAD

**Issue by celborn** [olehj/disklocation#202]
![image](https://user-images.githubusercontent.com/1553952/227429448-0fa72b2b-085c-442f-88e5-7f5e173387c4.png)

I am seeing the max temp of 12 degrees F and this is causing the drives to all flash.
I am running unraid 6.12 rc2 and Disk Location v 2023.03.24

**Comment by olehj** [comment]
Check that specific disk for what's set in Unraid. The warning and critical point is not configured by this plugin.

**Comment by celborn** [comment]
Derp.. thank you for pointing me in the right direction and thank you for
making a bad ass app

**Comment by olehj** [comment]
![Screenshot_20230324_204809](https://user-images.githubusercontent.com/3252328/227625269-13fd628e-f7d6-4e1d-9814-41e948e44afd.png)

check this..

**Comment by olehj** [comment]
![Screenshot_20230324_204953](https://user-images.githubusercontent.com/3252328/227625511-e7664e04-c30a-4010-8140-233e2268ba02.png)
check this :P

**Comment by olehj** [comment]
Was this solved for you?

**Comment by celborn** [comment]
Yes, it was thank you

**Comment by olehj** [comment]
Cool, closing it as fixed!
