### ISSUE TITLE
Request: Multiple cases

### ISSUE THREAD

**Issue by tarchive** [olehj/disklocation#22]
Hello First off thank you for this!

I'm sure you were counting the days before someone suggests this, but any chance of support for multiple cases? 

For my storage layout, my server has 5 vertical hot swap bays in the Unraid server and 24 horizontal hot swap bays in a separate expansion shelf. 

Disks 1-5 are in my server at the top of my rack and  6-29 are in my disk shelf directly below the server in the rack. If I could create a "Group A" consisting of a disks 1-5 in a 5x1 pattern and set orientation to vertical then a "Group B" consisting of 6-29 in a 6x4 pattern with the standard horizontal orientation, that would be perfect!

Since a picture is worth a 1000 words... 

![disk groupa](https://user-images.githubusercontent.com/26031707/51937201-024cb380-23d8-11e9-8563-fcef4d6587bb.png) | ![disk groupb](https://user-images.githubusercontent.com/26031707/51937208-07a9fe00-23d8-11e9-9f89-b1eea5046568.png)

Just a something i threw together to visualize what i had in mind. With any luck your coding is better than my mspaint skills and can make this request possible

**Comment by olehj** [comment]
There's no current plan for this, as the code probably need a massive redesign.

However, the use of "Override" should help you a bit even if it won't look exactly like your physical layout. I would suggest 4*6(24) + override set to 29(5), you will then get two individual groups. Override was created for this intention, and is quite a simple "hack" 

Check if that works for you. I'll leave this as a future enhancement, but I can't promise anything.

**Comment by tarchive** [comment]
Yeah, i am using those override now with okay results. It is not perfect in my situation because of the mix of even and odd columns in the physical server and shelf but this is still totally usable. I'll play around with layouts a bit more. Either way it beats using my spreadsheet to lookup drive information. I look forward to this enhancement if becomes advantageous
