### ISSUE TITLE
Crashing Dashboard

### ISSUE THREAD

**Issue by Buddy1673** [olehj/disklocation#220]
I've updated to UR 6.12.1 added back Disk location but it seems to crash the Dashboard unless all drives are spun-up, then it comes back.

**Comment by Buddy1673** [comment]
BTW love the plugin.

**Comment by olehj** [comment]
Please go to "Tools -> PHP Settings" then set reporting level to "All categories", you might also select the "Show errors on screen" too.

Then when all drives are spun down, then hopefully there's some errors and or warnings related to Disk Location plugin. Please post the relevant messages here.

Sadly I have no time to reproduce and debug this now, so this help could speed things up a bit.

**Comment by Buddy1673** [comment]
After I figured out hos to do it, here it is



SPUN-DOWN STATE ERROR (THIS SHOWED UP ON THE DASHBOARD)

Fatal error: Uncaught TypeError: round(): Argument #1 ($num) must be of type int|float, string given in /usr/local/emhttp/plugins/disklocation/pages/devices.php:295 Stack trace: #0 /usr/local/emhttp/plugins/disklocation/pages/devices.php(295): round('*') #1 /usr/local/emhttp/plugins/dynamix/include/DefaultPageLayout.php(706) : eval()'d code(25): require_once('/usr/local/emht...') #2 /usr/local/emhttp/plugins/dynamix/include/DefaultPageLayout.php(706): eval() #3 /usr/local/emhttp/plugins/dynamix/template.php(82): require_once('/usr/local/emht...') #4 {main} thrown in /usr/local/emhttp/plugins/disklocation/pages/devices.php on line 295



SPUN-UP STATE ERROR

[28-Jun-2023 13:12:38 America/Los_Angeles] PHP Fatal error:  Uncaught TypeError: round(): Argument #1 ($num) must be of type int|float, string given in /usr/local/emhttp/plugins/disklocation/pages/devices.php:295

**Comment by olehj** [comment]
> After I figured out hos to do it, here it is
> 
> SPUN-DOWN STATE ERROR (THIS SHOWED UP ON THE DASHBOARD)
> 
> Fatal error: Uncaught TypeError: round(): Argument #1 ($num) must be of type int|float, string given in /usr/local/emhttp/plugins/disklocation/pages/devices.php:295 Stack trace: #0 /usr/local/emhttp/plugins/disklocation/pages/devices.php(295): round('*') #1 /usr/local/emhttp/plugins/dynamix/include/DefaultPageLayout.php(706) : eval()'d code(25): require_once('/usr/local/emht...') #2 /usr/local/emhttp/plugins/dynamix/include/DefaultPageLayout.php(706): eval() #3 /usr/local/emhttp/plugins/dynamix/template.php(82): require_once('/usr/local/emht...') #4 {main} thrown in /usr/local/emhttp/plugins/disklocation/pages/devices.php on line 295
> 
> SPUN-UP STATE ERROR
> 
> [28-Jun-2023 13:12:38 America/Los_Angeles] PHP Fatal error: Uncaught TypeError: round(): Argument #1 ($num) must be of type int|float, string given in /usr/local/emhttp/plugins/disklocation/pages/devices.php:295

Thanks, I'll go through this now and release an update soon-ish. I can't test this myself right now, but I'll keep an eye on this.

**Comment by olehj** [comment]
Still not resolved apparently. Further debugging required.
