### ISSUE TITLE
Feature Request - Support for TBW similar to warranty date 

### ISSUE THREAD

**Issue by MTWiley** [olehj/disklocation#227]
Can we add a field/section for Warrantied TBW to support SSDs better?

With that field added a similar calculation to what you're doing for warranty dates:

`Entered date - Today's date = Remaining Warranty Days`

I suggest adding the Warrantied TBW field vs. the current SMART data value for total data written to the disk.
You could then use those values to calculate a TBW remaining value to be displayed similarly to how you show days remaining for the warranty.

`Warrantied TBW - SMART Data for TBW = Remaining TBW`

I'm happy to take a first swing at it if you want the development help. I'd like to avoid stepping on anyone's toes or wasting my time if you're not interested in adding it to the main project since I don't want to be responsible for maintaining a separate repo/fork of the project.

**Comment by olehj** [comment]
Added "percentage used" and other NVME SMART data to the plugin. Should cover TBW.. ish.

Upcoming in Update 2023.09.14
