### ISSUE TITLE
Feature Request: Turn off / rearrange columns

### ISSUE THREAD

**Issue by Karyudo** [olehj/disklocation#245]
Any time there's an array of information (under Allocations, Information, etc.) it would be nice to be able to rearrange or hide columns.

Personally, I don't care about info like "Path" or "Logical Unit Name," and while I'd like for that information to be available someplace, almost all of the time I'd want it hidden, to keep things simple.

It would also be handy to be able to move columns of interest beside each other. For example, I'd want to put Group, Tray ID, and then Friendly Name close together, so it's easy to see what's where.

**Comment by olehj** [comment]
This can be combined with #250 probably. Should just be a sorting configuration, the question is just how to implement it. Might be cookies for simplicity, but those can be a bit annoying to.
