### ISSUE TITLE
Feature Request: Algorithmically abbreviate serial numbers as 'friendly name'

### ISSUE THREAD

**Issue by Karyudo** [olehj/disklocation#246]
Because different manufacturers use serial numbers of different lengths, sorting and searching for drives can be tricky. I'd like to be able to have a "friendly name" for each drive, and use that rather than the full serial number for almost all actions. I use the last four characters of the serial number (regardless of brand), and that seems to work well for me.

**Comment by olehj** [comment]
Add the name under "Comment" for each drive?
