### ISSUE TITLE
Feature Request: Database field for 'Date of Manufacture'

### ISSUE THREAD

**Issue by Karyudo** [olehj/disklocation#249]
I know there are already Purchase Date and Warranty Date fields, but I've been tracking Manufacture Date, because it's printed on every drive. I'd like to be able to "officially" use that instead of Purchase Date.

**Comment by olehj** [comment]
I've always referred to others to use the "Purchase Date" as the "Manufacturing Date" if they need that instead. Usually only one of them matters for the end user and it is supposed to reflect numbers of days left until warranty expires. Those two dates are linked up to eachother. There's a comment field too, to add extra data.
