### ISSUE TITLE
Feature Request: Sort information by fields

### ISSUE THREAD

**Issue by Karyudo** [olehj/disklocation#250]
It would be nice to be able to sort information by various fields, for example, by Size, Date of Manufacture, Warranty Date, Power On Hours, or various things like that. If I buy a new large drive and want to swap it in for a smaller, older, healthy drive, which drive should I replace? Sorting to find the oldest, most-used drive quickly would be very handy.

**Comment by olehj** [comment]
It's been a thought I had since I started developing this, just didn't bother with it yet. I'll see what I can do "soon-ish", Valve-time™
