### ISSUE TITLE
Feature Request : Add SQL Column : Remove_Date, Remove_Comment, Remove_Status

### ISSUE THREAD

**Issue by sxb1n9** [olehj/disklocation#276]
Would like to ask if you could add 2-3 columns to the SQL TABLE for use in the history display as follows: 

Remove_Date = the date the disk is removed from the system
Remove_Comment = the comment on why the disk was removed from the system

The next one could be put in the comment, but I would like a flag for if the drive still works (aka can I use it still for a spare in a pinch or in another system where the data retention is not as critical)

Remove_Status = flag or int to store a status or id of a list of statuses such as (GOOD, GOOD w/ RS, BAD, UNKNOWN)

Finally I just thought about this so I am ninja editing this request for another column

Install_Date = the date it is installed in the system. 

Hope this all makes sense.   I usually put this information into the comment field when I remove a drive, but it would be nice to have fields for the history drives to keep track of them and their status.   

Thanks

**Comment by olehj** [comment]
"Install" and "remove" date could probably be added one day, but status and additional comment could just be written in the already existing comment field. It supports formatting and good stuff.

**Comment by olehj** [comment]
Installed date is added by user input. Removed will be automatically populated when it detects the drive is gone.
