### ISSUE TITLE
Text overflow border

### ISSUE THREAD

**Issue by libook** [olehj/disklocation#314]
![disklocation](https://github.com/olehj/disklocation/assets/3395610/0991e19f-32ca-4fcc-aa59-b71180191b59)

The default height is 70px, I changed it to 135px to get the following effect:

![disklocation(1)](https://github.com/olehj/disklocation/assets/3395610/6ae23ecf-fd39-422e-9a26-30c07dab077f)

Perhaps there is a better adaptive solution?

**Comment by olehj** [comment]
Probably, but can't be bothered. Hence why you have the possibility to adjust it :p
