### ISSUE TITLE
No overview Dashboard after installation

### ISSUE THREAD

**Issue by cryd-s** [olehj/disklocation#333]
![image](https://github.com/user-attachments/assets/3c9e7286-af7d-4a54-bf39-ac2e018cd500)

need help to get my start dashboard back

**Comment by cryd-s** [comment]
![image](https://github.com/user-attachments/assets/a1d1a8d4-7f5a-4742-8fbf-6c4c4506d60b)

**Comment by olehj** [comment]
Duplicate of #328 and #334
