### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by ptr727** [olehj/disklocation#65]
Great plugin, thank you.

```
Warning: count(): Parameter must be an array or an object that implements Countable in /usr/local/emhttp/plugins/disklocation/pages/system.php on line 389
```

There is a similar report, different source location:
https://github.com/olehj/disklocation/issues/38

I am running Unraid 6.6.7
Plugin version 2019.03.10

![2019-04-28 (6)](https://user-images.githubusercontent.com/2061579/56873601-515eb080-69e8-11e9-9ae5-1cd1a736686c.png)
![2019-04-28 (8)](https://user-images.githubusercontent.com/2061579/56874200-39d5f680-69ed-11e9-976e-d7121512d9e0.png)

**Comment by olehj** [comment]
This should have been fixed now, try the new update.
