### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by ljm42** [olehj/disklocation#92]
Thanks for this plugin!

I am running plugin version 2019.07.06 on Unraid 6.7.2

During bootup I see this message in the syslog:

`Warning: count(): Parameter must be an array or an object that implements Countable in /usr/local/emhttp/plugins/disklocation/pages/system.php on line 1088`

**Comment by olehj** [comment]
These things are haunting me :P anyway, will be uploaded soon

**Comment by ljm42** [comment]
pesky bugs :)  thanks for this!
